name: zeronet-js
version: 0.0.1
summary: ZeroNet in JS
description: |
  ZeroNet in JavaScript

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  zeronet-js:
    aliases:
      - zeronetjs
    command: bin/zeronet
    plugs:
      - network
      - network-bind

parts:
  node:
    plugin: nodejs
    node-engine: 8.9.1
    source: .
    build-packages:
      - python
      - g++
      - make
  strip-nondeterminism:
    plugin: nil
    source: .empty
    after:
      - zeronetjs
    build: |
      #HACK: reset the timestamp of every file
      find $SNAPCRAFT_STAGE -print0 | xargs -0i touch -a -m -t 200001010000.00 {}
