name: zeronet-js
version: 0.0.1
summary: ZeroNet in JS
description: |
  ZeroNet in JavaScript

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  zeronet-js:
    aliases:
      - zeronetjs
    command: bin/zeronet
    plugs:
      - network
      - network-bind

parts:
  znjs:
    plugin: nodejs
    node-engine: 8.9.1
    source: .
    build-packages:
      - python
      - g++
      - make
    build: |
      rm -rf .git/hooks
