name: zeronet-js
version: 0.0.1-alpha15
summary: ZeroNet in JS
description: |
  ZeroNet in JavaScript

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  zeronet-js:
    aliases:
      - zeronetjs
    command: bin/zeronet
    plugs:
      - network
      - network-bind

parts:
  node:
    plugin: nodejs
    node-engine: 8.2.1
    source: .empty
    build-packages:
      - python
      - g++
      - make
  source:
    plugin: nil
    after:
      - node
    source: .
    build: |
      set -e
      bash scripts/tarball.sh
    install: |
      set -e
      TMP=/tmp/zeronet-js-build
      rm -rf $TMP
      mkdir -p $TMP/.{npm,node_gyp}
      npm_config_cache="$TMP/.npm" npm_config_devdir="$TMP/.node-gyp" npm_config_prefix="$SNAPCRAFT_PART_INSTALL" npm shrinkwrap
      node scripts/no-git-deps.js npm-shrinkwrap.json
      node scripts/no-dev-deps.js npm-shrinkwrap.json > /dev/null
      npm_config_cache="$TMP/.npm" npm_config_devdir="$TMP/.node-gyp" npm_config_prefix="$SNAPCRAFT_PART_INSTALL" bash scripts/global.sh
      rm -rf $TMP
  strip-nondeterminism:
    plugin: nil
    source: .empty
    after:
      - source
    build: |
      #HACK: reset the timestamp of every file
      find $SNAPCRAFT_STAGE -print0 | xargs -0i touch -a -m -t 200001010000.00 {}
